0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,27 +1,27 @@
 #!/usr/bin/env bash
-# checking for parameters
+# checking for command line arguments
 
-if [$# -lt 4]
+if [ $# -lt 4 ]
 then
 	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 	exit 1
 fi
 
-# allocating parameters to variables
+# assigning parameters to variables
 
 path_to_file=$1
 ip=$2
 username=$3
 path_to_ssh_key=$4
 
-# disabling strct host key checking
+# disabbling strict host key checking
 
 scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-# checking if the file transfered was successful
-if [ $? -eq 0]
+# checking if the transfer was successful
+if [ $? -eq 0 ]
 then
-	echo "TRANSFER WAS SUCCESSFUL"
+	echo "FILE WAS TRANSFERED SUCCESSFULLY"
 else
-	echo "TRANSFER FAILED"
+	echo "FILE TRANSFERWAS FAILED"
 fi
